export enum TokenType {
	EOF = 'EOF',
	InlineHtml = 'InlineHtml',
	OpenTag = 'OpenTag',
	OpenTagWithEcho = 'OpenTagWithEcho',
	CloseTag = 'CloseTag',

	Variable = 'Variable',
	Identifier = 'Identifier',
	Integer = 'Integer',
	Float = 'Float',
	String = 'String',
	HeredocStart = 'HeredocStart',
	HeredocEnd = 'HeredocEnd',
	NowdocStart = 'NowdocStart',
	NowdocEnd = 'NowdocEnd',
	EncapsedString = 'EncapsedString',
	StringPart = 'StringPart',
	EncapsedOpen = 'EncapsedOpen',
	EncapsedClose = 'EncapsedClose',
	Comment = 'Comment',
	DocComment = 'DocComment',

	Abstract = 'Abstract',
	And = 'And',
	Array = 'Array',
	As = 'As',
	Break = 'Break',
	Callable = 'Callable',
	Case = 'Case',
	Catch = 'Catch',
	Class = 'Class',
	Clone = 'Clone',
	Const = 'Const',
	Continue = 'Continue',
	Declare = 'Declare',
	Default = 'Default',
	Do = 'Do',
	Echo = 'Echo',
	Else = 'Else',
	Elseif = 'Elseif',
	Empty = 'Empty',
	Enddeclare = 'Enddeclare',
	Endfor = 'Endfor',
	Endforeach = 'Endforeach',
	Endif = 'Endif',
	Endswitch = 'Endswitch',
	Endwhile = 'Endwhile',
	Enum = 'Enum',
	Eval = 'Eval',
	Exit = 'Exit',
	Extends = 'Extends',
	Final = 'Final',
	Finally = 'Finally',
	Fn = 'Fn',
	For = 'For',
	Foreach = 'Foreach',
	Function = 'Function',
	Global = 'Global',
	Goto = 'Goto',
	If = 'If',
	Implements = 'Implements',
	Include = 'Include',
	IncludeOnce = 'IncludeOnce',
	Instanceof = 'Instanceof',
	Insteadof = 'Insteadof',
	Interface = 'Interface',
	Isset = 'Isset',
	List = 'List',
	Match = 'Match',
	Namespace = 'Namespace',
	New = 'New',
	Or = 'Or',
	Print = 'Print',
	Private = 'Private',
	Protected = 'Protected',
	Public = 'Public',
	Readonly = 'Readonly',
	Require = 'Require',
	RequireOnce = 'RequireOnce',
	Return = 'Return',
	Static = 'Static',
	Switch = 'Switch',
	Throw = 'Throw',
	Trait = 'Trait',
	Try = 'Try',
	Unset = 'Unset',
	Use = 'Use',
	Var = 'Var',
	While = 'While',
	Xor = 'Xor',
	Yield = 'Yield',
	YieldFrom = 'YieldFrom',

	Plus = 'Plus',
	Minus = 'Minus',
	Asterisk = 'Asterisk',
	Slash = 'Slash',
	Percent = 'Percent',
	Pow = 'Pow',

	Assign = 'Assign',
	PlusAssign = 'PlusAssign',
	MinusAssign = 'MinusAssign',
	MulAssign = 'MulAssign',
	DivAssign = 'DivAssign',
	ModAssign = 'ModAssign',
	PowAssign = 'PowAssign',
	ConcatAssign = 'ConcatAssign',
	AndAssign = 'AndAssign',
	OrAssign = 'OrAssign',
	XorAssign = 'XorAssign',
	ShiftLeftAssign = 'ShiftLeftAssign',
	ShiftRightAssign = 'ShiftRightAssign',
	NullCoalesceAssign = 'NullCoalesceAssign',

	Equal = 'Equal',
	Identical = 'Identical',
	NotEqual = 'NotEqual',
	NotIdentical = 'NotIdentical',
	LessThan = 'LessThan',
	GreaterThan = 'GreaterThan',
	LessThanOrEqual = 'LessThanOrEqual',
	GreaterThanOrEqual = 'GreaterThanOrEqual',
	Spaceship = 'Spaceship',

	BooleanAnd = 'BooleanAnd',
	BooleanOr = 'BooleanOr',
	Not = 'Not',

	Ampersand = 'Ampersand',
	Pipe = 'Pipe',
	Caret = 'Caret',
	Tilde = 'Tilde',
	ShiftLeft = 'ShiftLeft',
	ShiftRight = 'ShiftRight',

	NullCoalesce = 'NullCoalesce',
	Arrow = 'Arrow',
	NullsafeArrow = 'NullsafeArrow',
	DoubleColon = 'DoubleColon',
	Increment = 'Increment',
	Decrement = 'Decrement',
	ErrorSuppress = 'ErrorSuppress',
	Ellipsis = 'Ellipsis',
	DoubleArrow = 'DoubleArrow',
	AttributeStart = 'AttributeStart',

	OpenParen = 'OpenParen',
	CloseParen = 'CloseParen',
	OpenBrace = 'OpenBrace',
	CloseBrace = 'CloseBrace',
	OpenBracket = 'OpenBracket',
	CloseBracket = 'CloseBracket',
	Semicolon = 'Semicolon',
	Comma = 'Comma',
	Dot = 'Dot',
	Question = 'Question',
	Colon = 'Colon',
	Backslash = 'Backslash',
}

export interface Position {
	line: number;
	column: number;
	offset: number;
}

export interface Token {
	type: TokenType;
	value: string;
	start: Position;
	end: Position;
}

export function createToken(type: TokenType, value: string, start: Position, end: Position): Token {
	return { type, value, start, end };
}

export const KEYWORDS: ReadonlyMap<string, TokenType> = new Map([
	['abstract', TokenType.Abstract],
	['and', TokenType.And],
	['array', TokenType.Array],
	['as', TokenType.As],
	['break', TokenType.Break],
	['callable', TokenType.Callable],
	['case', TokenType.Case],
	['catch', TokenType.Catch],
	['class', TokenType.Class],
	['clone', TokenType.Clone],
	['const', TokenType.Const],
	['continue', TokenType.Continue],
	['declare', TokenType.Declare],
	['default', TokenType.Default],
	['do', TokenType.Do],
	['echo', TokenType.Echo],
	['else', TokenType.Else],
	['elseif', TokenType.Elseif],
	['empty', TokenType.Empty],
	['enddeclare', TokenType.Enddeclare],
	['endfor', TokenType.Endfor],
	['endforeach', TokenType.Endforeach],
	['endif', TokenType.Endif],
	['endswitch', TokenType.Endswitch],
	['endwhile', TokenType.Endwhile],
	['enum', TokenType.Enum],
	['eval', TokenType.Eval],
	['exit', TokenType.Exit],
	['extends', TokenType.Extends],
	['final', TokenType.Final],
	['finally', TokenType.Finally],
	['fn', TokenType.Fn],
	['for', TokenType.For],
	['foreach', TokenType.Foreach],
	['function', TokenType.Function],
	['global', TokenType.Global],
	['goto', TokenType.Goto],
	['if', TokenType.If],
	['implements', TokenType.Implements],
	['include', TokenType.Include],
	['include_once', TokenType.IncludeOnce],
	['instanceof', TokenType.Instanceof],
	['insteadof', TokenType.Insteadof],
	['interface', TokenType.Interface],
	['isset', TokenType.Isset],
	['list', TokenType.List],
	['match', TokenType.Match],
	['namespace', TokenType.Namespace],
	['new', TokenType.New],
	['or', TokenType.Or],
	['print', TokenType.Print],
	['private', TokenType.Private],
	['protected', TokenType.Protected],
	['public', TokenType.Public],
	['readonly', TokenType.Readonly],
	['require', TokenType.Require],
	['require_once', TokenType.RequireOnce],
	['return', TokenType.Return],
	['static', TokenType.Static],
	['switch', TokenType.Switch],
	['throw', TokenType.Throw],
	['trait', TokenType.Trait],
	['try', TokenType.Try],
	['unset', TokenType.Unset],
	['use', TokenType.Use],
	['var', TokenType.Var],
	['while', TokenType.While],
	['xor', TokenType.Xor],
	['yield', TokenType.Yield],
]);
